version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "0.0.0.0:5433:5432"
